"""empty message

Revision ID: 190245a8c2d4
Revises: 
Create Date: 2024-11-11 01:43:55.923014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190245a8c2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('año_publicacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libro')
    # ### end Alembic commands ###
